server:
  port: 3355
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址 Map
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: true # true表示将自己注册进EurekaServer 默认为true
    fetch-registry: true #是否从EurekaServer抓取己有的注册信息，默认为true，单节点无所谓，集群必须设置为true才以配合riboon使用负载均衡
