server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功有，利用微服务名进行路由
#      routes:
#      - id: payment_routh          #路由ID，没有固定规则但要求唯一，建议配合服务名
#        #uri: http://localhost:8001   #匹配后提供服务的路由地址
#        uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #匹配后提供的路由地址
#        predicates:
#        - Path=/payment/circuit/**   #断言，路径相匹配的进行路由
#      - id: payment_routh2
#        uri: http://localhost:8001
#        predicates:
#        - Path=/payment/lb/**
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址 Map
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: true # true表示将自己注册进EurekaServer 默认为true
    fetch-registry: true #是否从EurekaServer抓取己有的注册信息，默认为true，单节点无所谓，集群必须设置为true才以配合riboon使用负载均衡
  instance:
    hostname: cloud-gateway-service
