
spring:
  application:
    name: stream-sink

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        goods-in:
          destination: goods # 对应的topic
          contentType: application/json
          group: finance # 指定消费者组
      default-binder: kafka  #与consul 使用时需要指定 binder
server:
  port: 8802